"""empty message

Revision ID: 4c05f121d0ba
Revises: 48a9cf74d68e
Create Date: 2025-05-22 16:55:31.672904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c05f121d0ba'
down_revision = '48a9cf74d68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('time_of_eat',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('type_of_dish',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('type_of_dish',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('time_of_eat',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
